Repository CA-G12/E-commerce-Team-9, pull requests merged in 2022-09, with the labels that each got.

#2 Create file structure for the client and server
  .env.example
  .eslintrc.js
  .gitignore
  client/.eslintrc.js
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/products/index.js
  server/controllers/register/index.js
  server/controllers/register/login.js
  server/controllers/register/logout.js
  server/controllers/register/signup.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/seeder.sql
  server/database/queries/index.js
  server/database/queries/products/index.js
  server/database/queries/register/index.js
  server/database/queries/register/loginQuery.js
  server/database/queries/register/signuoQuery.js
  server/index.js
  server/middlewares/verifyToken.js
  server/routers/index.js
  server/utils/heplers/GenericError.js
  server/utils/heplers/generateToken.js
  server/utils/heplers/index.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/loginValidate.js
  server/utils/validation/signupValidate.js
  server/utils/validation/validator.js
Labels: approved

#4 Build connection and write the middleware needed for the token verifi…
  client/.eslintrc.js
  package-lock.json
  package.json
  server/database/config/connection.js
  server/middlewares/verifyToken.js
Labels: approved

#6 create database tables and realations with fake data insertion
  .eslintrc.js
  client/package.json
  server/database/config/build.sql
  server/database/config/seeder.sql
Labels: approved

#12 Make the signup and login queries, then make their functions
  server/app.js
  server/controllers/index.js
  server/controllers/register/index.js
  server/controllers/register/login.js
  server/controllers/register/signup.js
  server/database/queries/index.js
  server/database/queries/register/index.js
  server/database/queries/register/loginQuery.js
  server/database/queries/register/selectUserByEmail.js
  server/database/queries/register/signuoQuery.js
  server/database/queries/register/signupQuery.js
  server/routers/index.js
  server/utils/helpers/CustomError.js
  server/utils/helpers/generateToken.js
  server/utils/helpers/index.js
  server/utils/heplers/GenericError.js
  server/utils/heplers/generateToken.js
  server/utils/heplers/index.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/loginValidate.js
  server/utils/validation/signupValidate.js
  server/utils/validation/validator.js
Labels: approved

#9 create get all products
  server/app.js
  server/controllers/index.js
  server/controllers/products/getAllProducts.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/getAllProductsQuery.js
  server/database/queries/products/index.js
  server/routers/index.js
  server/routers/products.js
Labels: approved

#13 get all products and delete and add product to cart
  server/app.js
  server/controllers/index.js
  server/controllers/products/addNewProductToCart.js
  server/controllers/products/deleteProductById.js
  server/controllers/products/getUserProductsById.js
  server/controllers/products/index.js
  server/database/config/build.sql
  server/database/config/seeder.sql
  server/database/queries/index.js
  server/database/queries/products/addNewProductToCart.js
  server/database/queries/products/deleteProductById.js
  server/database/queries/products/getUserProductsById.js
  server/database/queries/products/index.js
  server/routers/index.js
Labels: awaiting-review

#14 get, add, delete form cart page
  server/app.js
  server/controllers/index.js
  server/controllers/products/addNewProductToCart.js
  server/controllers/products/deleteProductById.js
  server/controllers/products/getUserProductsById.js
  server/controllers/register/index.js
  server/controllers/register/logout.js
  server/controllers/register/signup.js
  server/database/config/build.sql
  server/database/config/seeder.sql
  server/database/queries/products/addNewProductToCart.js
  server/database/queries/products/deleteProductById.js
  server/middlewares/verifyToken.js
  server/routers/index.js
Labels: approved

#16 Add queries and functions for products filtered by category and price
  server/app.js
  server/controllers/index.js
  server/controllers/products/filterByPrice.js
  server/controllers/products/filterProductsByCategory.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/filterByPriceQuery.js
  server/database/queries/products/filterProductCategoryQuery.js
  server/database/queries/products/index.js
  server/routers/index.js
  server/routers/products.js
Labels: approved

#18 Setting up all the components needed
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/cart/Catrt.jsx
  client/src/components/index.js
  client/src/components/landingPage/Card/CardContainer.jsx
  client/src/components/landingPage/Card/ProductCard.jsx
  client/src/components/landingPage/Filter/Aside.jsx
  client/src/components/landingPage/Filter/CategoryFilter.jsx
  client/src/components/landingPage/Filter/PriceFilter.jsx
  client/src/components/landingPage/Header.jsx
  client/src/components/landingPage/LandingPage.jsx
  client/src/components/landingPage/logo.png
  client/src/components/login/Login.jsx
  client/src/components/productDetails/ProductPage.jsx
  client/src/components/signup/Signup.jsx
  client/src/index.js
  client/src/style/card.css
  client/src/style/cart.css
  client/src/style/details.css
  client/src/style/landingPage.css
  client/src/style/login.css
  client/src/style/signup.css
  package-lock.json
  server/app.js
Labels: approved

#23 21 create login signup
  client/src/components/login/Login.jsx
  client/src/components/signup/Asos-black-logo.png
  client/src/components/signup/Signup.jsx
  client/src/style/login.css
  client/src/style/signup.css
Labels: approved

#22 create landing page and style it
  client/src/components/landingPage/Card/CardContainer.jsx
  client/src/components/landingPage/Card/ProductCard.jsx
  client/src/components/landingPage/Filter/CategoryFilter.jsx
  client/src/components/landingPage/Filter/PriceFilter.jsx
  client/src/components/landingPage/Header.jsx
  client/src/components/landingPage/LandingPage.jsx
  client/src/style/card.css
  client/src/style/landingPage.css
  server/routers/index.js
Labels: awaiting-review

#26 Handled signup and login fetching using axios
  client/package-lock.json
  client/package.json
  client/src/components/login/Login.jsx
  client/src/components/signup/Signup.jsx
  client/src/index.js
  client/src/style/login.css
  client/src/style/signup.css
Labels: approved

#27 fetch all data in the landing page
  client/src/components/landingPage/Card/CardContainer.jsx
  client/src/components/landingPage/Card/ProductCard.jsx
  client/src/components/landingPage/Filter/CategoryFilter.jsx
  client/src/components/login/Login.jsx
  client/src/components/signup/Signup.jsx
  client/src/style/card.css
  client/src/style/landingPage.css
  package-lock.json
  package.json
  server/app.js
  server/database/config/seeder.sql
Labels: approved

#30 adding details for spesific product
  client/src/components/landingPage/Card/ProductCard.jsx
  client/src/components/productDetails/ProductPage.jsx
  client/src/index.js
  server/controllers/index.js
  server/controllers/products/getProductDetails.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/getProductDetails.js
  server/database/queries/products/index.js
  server/routers/index.js
Labels: done

#32 fetched ascending and descending price data
  client/src/components/landingPage/Card/CardContainer.jsx
  client/src/components/landingPage/Filter/Aside.jsx
  client/src/components/landingPage/Filter/PriceFilter.jsx
  client/src/components/landingPage/Header.jsx
  client/src/components/landingPage/LandingPage.jsx
  client/src/components/login/Login.jsx
  client/src/index.js
  client/src/style/card.css
  client/src/style/landingPage.css
  server/database/config/seeder.sql
Labels: awaiting-review

#33 change set state for the prices
  client/src/components/landingPage/LandingPage.jsx
  client/src/components/productDetails/ProductPage.jsx
Labels: approved

#35 Fixing some style
  client/src/style/login.css
Labels: merged

#36 Fetch addTo cart function
  client/src/components/productDetails/ProductPage.jsx
  server/controllers/products/addNewProductToCart.js
  server/database/config/build.sql
  server/database/config/seeder.sql
  server/database/queries/products/addNewProductToCart.js
Labels: approved

#38 createing cart page and handle delete product
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/components/cart/Cart.jsx
  client/src/components/landingPage/Filter/PriceFilter.jsx
  client/src/components/login/Login.jsx
  client/src/components/productDetails/ProductPage.jsx
  client/src/components/signup/Signup.jsx
  client/src/index.js
  client/src/style/cart.css
  package-lock.json
  package.json
  server/controllers/products/getUserProductsById.js
  server/database/queries/products/getUserProductsById.js
Labels: approved

#40 39 fixing style
  client/src/components/productDetails/ProductPage.jsx
  client/src/style/details.css
Labels: awaiting-review

#42 Fixing some styling in the landing page
  .eslintrc.js
  client/src/components/cart/Cart.jsx
  client/src/components/landingPage/Filter/Aside.jsx
  client/src/components/landingPage/Filter/CategoryFilter.jsx
  client/src/components/landingPage/Filter/PriceFilter.jsx
  client/src/style/card.css
  client/src/style/cart.css
  client/src/style/landingPage.css
Labels: approved

#44 search filter and logout
  .vscode/settings.json
  client/src/components/cart/Cart.jsx
  client/src/components/handleErros/Spinner.js
  client/src/components/handleErros/Unauthorized .js
  client/src/components/landingPage/Card/CardContainer.jsx
  client/src/components/landingPage/Filter/CategoryFilter.jsx
  client/src/components/landingPage/Header.jsx
  client/src/components/landingPage/LandingPage.jsx
  client/src/components/productDetails/ProductPage.jsx
  client/src/style/cart.css
  client/src/style/details.css
  client/src/style/spinner.css
  server/controllers/products/getAllProducts.js
  server/controllers/products/getUserProductsById.js
  server/controllers/register/login.js
  server/middlewares/verifyToken.js
  server/routers/index.js
Labels: approved
